import { StyleSheet } from "react-native";


export default styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  mainHeaderText: {
    fontSize: 18,
    fontWeight: "bold",
  },
  topBarHeaderContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 10,
    paddingLeft: 24,
    paddingRight: 24,
  },
  isSettingModalContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
  },
  inputTypeCardContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    padding: 10,
    marginLeft: "2%",
  },
  inputTypeCard: {
    width: '48%', 
    height: 200, 
    marginBottom: 20, 
    padding: 20,
    backgroundColor: "#f1f1f1",
    justifyContent: 'space-evenly',
    alignItems: 'center',
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  inputTypeCloseBtn: {
    position: "absolute",
    top: 72,
    right: 36,
    zIndex: 2,
    shadowColor: '#010101',
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  settingHeaderText: {
    color: '#010101',
    fontSize: 28,
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 12,
  },
  languageChangerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginLeft: 12,
    marginRight: 12,
    marginTop: 12,
    borderRadius: 50,
    paddingRight: 36,
    paddingLeft: 36,
    height: 72,
    gap:12,
    // backgroundColor: '#ffffff',
    // borderWidth: 0.25,
    // borderColor: 'white',
  },
  languageChangerInput: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    paddingLeft: 12,
    borderRadius: 20,
    width: 128,
    height: 56,
    shadowColor: '#010101',
    shadowOffset: {
      width: 3,
      height: 3,
    },
    shadowOpacity: 1,
    shadowRadius: 6,
    shadowColor: 'rgba(255, 255, 255, 0.5)', 
    shadowOffset: {
      width: -3,
      height: -3,
    },
    shadowOpacity: 1,
    shadowRadius: 6,
  },
  languageChangerModalContainer: {
    flex: 1,
    color: "black",
    justifyContent: 'flex-end',
  },
  languageChangerButtonContainer: {
    flex: 0.25,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'flex-end',
    marginBottom: 36,
  },
  languageChangerButton: {
    borderColor: '#010101',
    borderWidth: 0.25,
    borderRadius: 10,
    padding: 10,
    margin: 10,
    height: "24%",
    width: "20%",
    textAlign: 'center',
  },
  languageButtonText: {
    color: "white",
    fontWeight: "bold",
    textAlign: 'center',
  },
  languageChangerModalContainer: {
    flex: 1,
    color: "black",
    justifyContent: 'flex-end',
  },
  translateFieldContainer: {
    flex:0.5,
    flexDirection: "column",
    justifyContent: 'space-between',
    alignItems: "center",
    padding: 10,
  },
  textInputFieldTopBar: {
    flexDirection: "row",
    height: 42,
    justifyContent: "space-between",  
    alignItems: "center",
    paddingHorizontal: 10,  
    borderBottomColor: '#f1f1f1',
    borderBottomWidth: 0.25,
    paddingBottom: 12,
  },
  textInputField:{
    height: 175,
    width: "100%",
    borderColor: 'gray', 
    borderWidth: 0.25, 
    margin:12,
    padding: 12,
    shadowColor: '#CCDCE8',
    shadowOffset: {
      width: 3,
      height: 3,
    },
    shadowOpacity: 1,
    shadowRadius: 6,
    shadowColor: 'rgba(255, 255, 255, 0.5)', // This mimics the second inset shadow
    shadowOffset: {
      width: 3,
      height: 3,
    },
    shadowOpacity: 1,
    shadowRadius: 6,
  },
  translatedText: {
    fontSize: 14,
    color: "#010101",
  },
  translatedTextContainer: {
    backgroundColor: "#2A36AF",
    height:250,
    width: "100%",
    borderRadius: 20,
    padding: 12,
    marginTop: 24,
    shadowColor: '#CCDCE8',
    shadowOffset: {
      width: 3,
      height: 3,
    },
    shadowOpacity: 1,
    shadowRadius: 6,
    shadowColor: 'rgba(255, 255, 255, 0.5)', // This mimics the second inset shadow
    shadowOffset: {
      width: 3,
      height: 3,
    },
    shadowOpacity: 1,
    shadowRadius: 6,
  }, 
  cameraModalCloseButton: {
    position: "absolute",
    top: 56,
    right: 24,
    zIndex: 2,
  },
  cameraModalCaptureBtn: {
    padding: 6,
    borderRadius: 100,
    backgroundColor: '#f1f1f1',
    zIndex: 50,
  },
  cameraModalCaptureBtnContainer: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginBottom: 36,
  },
  downloadFileButton: {
    shadowColor: '#CCDCE8',
    shadowOffset: {
      width: 3,
      height: 3,
    },
    shadowOpacity: 1,
    shadowRadius: 6,
    shadowColor: 'rgba(255, 255, 255, 0.5)', // This mimics the second inset shadow
    shadowOffset: {
      width: 3,
      height: 3,
    },
    shadowOpacity: 1,
    shadowRadius: 6,
    borderWidth:0.25,
    borderColor: '#010101',
    borderRadius: 20,

  }

}
)